/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Data.Familia;
import Data.Linea;
import Data.Producto;
import Data.UnidadMedida;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Cachi
 */
public class IngresoProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterfazProducto
     */
    public IngresoProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager1 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("Proyecto2PU").createEntityManager();
        Proyecto2PUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("Proyecto2PU").createEntityManager();
        unidadMedidaQuery = java.beans.Beans.isDesignTime() ? null : Proyecto2PUEntityManager.createQuery("SELECT u FROM UnidadMedida u");
        unidadMedidaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : unidadMedidaQuery.getResultList();
        lineaQuery = java.beans.Beans.isDesignTime() ? null : Proyecto2PUEntityManager.createQuery("SELECT l FROM Linea l");
        lineaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : lineaQuery.getResultList();
        lineaQuery1 = java.beans.Beans.isDesignTime() ? null : Proyecto2PUEntityManager.createQuery("SELECT l FROM Linea l");
        lineaList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : lineaQuery1.getResultList();
        familiaQuery = java.beans.Beans.isDesignTime() ? null : Proyecto2PUEntityManager.createQuery("SELECT f FROM Familia f");
        familiaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : familiaQuery.getResultList();
        lb_codigo_barra = new javax.swing.JLabel();
        lb_nombre = new javax.swing.JLabel();
        lb_unidad_medida = new javax.swing.JLabel();
        lb_marca = new javax.swing.JLabel();
        lb_formato = new javax.swing.JLabel();
        lb_linea = new javax.swing.JLabel();
        lb_familia = new javax.swing.JLabel();
        tf_codigo_barra = new javax.swing.JTextField();
        tf_nombre_producto = new javax.swing.JTextField();
        cb_unidad_medida = new javax.swing.JComboBox<>();
        tf_nombre_marca = new javax.swing.JTextField();
        tf_formato_nombre = new javax.swing.JTextField();
        cb_linea_definicion = new javax.swing.JComboBox<>();
        cb_familia_definicion = new javax.swing.JComboBox<>();
        bt_guardar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        lb_codigo_barra.setText("Codigo Barra");

        lb_nombre.setText("Nombre");

        lb_unidad_medida.setText("Unidad de medida ");

        lb_marca.setText("Marca");

        lb_formato.setText("Formato");

        lb_linea.setText("Linea");

        lb_familia.setText("Familia");

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, unidadMedidaList, cb_unidad_medida);
        bindingGroup.addBinding(jComboBoxBinding);
        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cb_unidad_medida, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.descripcion}"), cb_unidad_medida, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lineaList1, cb_linea_definicion);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cb_linea_definicion, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.nombre}"), cb_linea_definicion, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, familiaList, cb_familia_definicion);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cb_familia_definicion, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.nombre}"), cb_familia_definicion, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        bt_guardar.setText("Guardar");
        bt_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel8.setText("Ingreso de Producto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_unidad_medida)
                    .addComponent(lb_codigo_barra, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_nombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_marca, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_formato, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_linea, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_familia, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_codigo_barra)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombre_producto)
                            .addComponent(cb_unidad_medida, 0, 140, Short.MAX_VALUE)
                            .addComponent(tf_nombre_marca)
                            .addComponent(tf_formato_nombre)
                            .addComponent(cb_linea_definicion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_familia_definicion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(bt_guardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_codigo_barra)
                    .addComponent(tf_codigo_barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nombre)
                    .addComponent(tf_nombre_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_unidad_medida)
                    .addComponent(cb_unidad_medida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_marca)
                    .addComponent(tf_nombre_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_formato)
                    .addComponent(tf_formato_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_linea)
                    .addComponent(cb_linea_definicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_familia)
                    .addComponent(cb_familia_definicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_guardar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarActionPerformed
          entityManager1.getTransaction().begin();
        Date d = new Date();
        Producto u = new Producto();
        u.setCodigoBarra(Integer.parseInt(tf_codigo_barra.getText()));
        u.setNombre(tf_nombre_producto.getText());
        u.setMarca(tf_nombre_marca.getText());
        u.setFormato(tf_formato_nombre.getText());
        u.setCreadoEl(d);
        u.setModificadoEl(d);
        u.setEliminadoEl(d);
        UnidadMedida un = (UnidadMedida)cb_unidad_medida.getSelectedItem();
        u.setUnidadMedidaId(un);
        Linea l = (Linea)cb_linea_definicion.getSelectedItem();
        u.setLineaId(l);
        Familia fa = (Familia)cb_familia_definicion.getSelectedItem();
        u.setFamiliaId(fa);
        JOptionPane.showMessageDialog(null,"Se a guardado correctamente");
        this.dispose();
        
        entityManager1.persist(u);
        entityManager1.flush();
        entityManager1.getTransaction().commit();
        entityManager1.close();
    }//GEN-LAST:event_bt_guardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager Proyecto2PUEntityManager;
    private javax.swing.JButton bt_guardar;
    private javax.swing.JComboBox<String> cb_familia_definicion;
    private javax.swing.JComboBox<String> cb_linea_definicion;
    private javax.swing.JComboBox<String> cb_unidad_medida;
    private javax.persistence.EntityManager entityManager1;
    private java.util.List<Data.Familia> familiaList;
    private javax.persistence.Query familiaQuery;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lb_codigo_barra;
    private javax.swing.JLabel lb_familia;
    private javax.swing.JLabel lb_formato;
    private javax.swing.JLabel lb_linea;
    private javax.swing.JLabel lb_marca;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JLabel lb_unidad_medida;
    private java.util.List<Data.Linea> lineaList;
    private java.util.List<Data.Linea> lineaList1;
    private javax.persistence.Query lineaQuery;
    private javax.persistence.Query lineaQuery1;
    private javax.swing.JTextField tf_codigo_barra;
    private javax.swing.JTextField tf_formato_nombre;
    private javax.swing.JTextField tf_nombre_marca;
    private javax.swing.JTextField tf_nombre_producto;
    private java.util.List<Data.UnidadMedida> unidadMedidaList;
    private javax.persistence.Query unidadMedidaQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
