/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Data.Familia;
import Data.Linea;
import Data.Producto;
import Data.UnidadMedida;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.persistence.Query;
import javax.swing.JOptionPane;

/**
 *
 * @author Diseño Cachi Codigo Matias
 */
public class IngresoProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterfazProducto
     */
    public IngresoProducto() {
        initComponents();
    }
    private int idproducto = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager1 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("Proyecto2PU").createEntityManager();
        Proyecto2PUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("Proyecto2PU").createEntityManager();
        unidadMedidaQuery = java.beans.Beans.isDesignTime() ? null : Proyecto2PUEntityManager.createQuery("SELECT u FROM UnidadMedida u");
        unidadMedidaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : unidadMedidaQuery.getResultList();
        lineaQuery = java.beans.Beans.isDesignTime() ? null : Proyecto2PUEntityManager.createQuery("SELECT l FROM Linea l");
        lineaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : lineaQuery.getResultList();
        lineaQuery1 = java.beans.Beans.isDesignTime() ? null : Proyecto2PUEntityManager.createQuery("SELECT l FROM Linea l");
        lineaList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : lineaQuery1.getResultList();
        familiaQuery = java.beans.Beans.isDesignTime() ? null : Proyecto2PUEntityManager.createQuery("SELECT f FROM Familia f");
        familiaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : familiaQuery.getResultList();
        lb_codigo_barra = new javax.swing.JLabel();
        lb_nombre = new javax.swing.JLabel();
        lb_unidad_medida = new javax.swing.JLabel();
        lb_marca = new javax.swing.JLabel();
        lb_formato = new javax.swing.JLabel();
        lb_linea = new javax.swing.JLabel();
        lb_familia = new javax.swing.JLabel();
        tf_codigo_barra = new javax.swing.JTextField();
        tf_nombre_producto = new javax.swing.JTextField();
        cb_unidad_medida = new javax.swing.JComboBox<>();
        tf_nombre_marca = new javax.swing.JTextField();
        tf_formato_nombre = new javax.swing.JTextField();
        cb_linea_definicion = new javax.swing.JComboBox<>();
        cb_familia_definicion = new javax.swing.JComboBox<>();
        bt_guardar = new javax.swing.JButton();
        lb_titulo = new javax.swing.JLabel();
        bt_editar = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        bt_buscar = new javax.swing.JButton();

        lb_codigo_barra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_codigo_barra.setText("Codigo Barra :");

        lb_nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_nombre.setText("Nombre :");

        lb_unidad_medida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_unidad_medida.setText("Unidad de medida :");

        lb_marca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_marca.setText("Marca :");

        lb_formato.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_formato.setText("Formato :");

        lb_linea.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_linea.setText("Linea :");

        lb_familia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_familia.setText("Familia :");

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, unidadMedidaList, cb_unidad_medida);
        bindingGroup.addBinding(jComboBoxBinding);
        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cb_unidad_medida, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.descripcion}"), cb_unidad_medida, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lineaList1, cb_linea_definicion);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cb_linea_definicion, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.nombre}"), cb_linea_definicion, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, familiaList, cb_familia_definicion);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cb_familia_definicion, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.nombre}"), cb_familia_definicion, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        bt_guardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_guardar.setText("Guardar");
        bt_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarActionPerformed(evt);
            }
        });

        lb_titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_titulo.setText("Ingreso de Producto");

        bt_editar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_editar.setText("Guardar Nuevos Cambios");
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        bt_eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_eliminar.setText("Eliminar");

        bt_buscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_buscar.setText("Buscar");
        bt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(lb_titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_linea)
                                    .addComponent(lb_familia))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cb_linea_definicion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb_familia_definicion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_nombre)
                                    .addComponent(lb_unidad_medida)
                                    .addComponent(lb_codigo_barra)
                                    .addComponent(lb_marca)
                                    .addComponent(lb_formato))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_nombre_producto, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(cb_unidad_medida, 0, 140, Short.MAX_VALUE)
                                    .addComponent(tf_nombre_marca, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(tf_formato_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(tf_codigo_barra))))))
                .addGap(0, 128, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bt_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_titulo)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_codigo_barra)
                            .addComponent(tf_codigo_barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_nombre)
                            .addComponent(tf_nombre_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_unidad_medida)
                            .addComponent(cb_unidad_medida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_marca)
                            .addComponent(tf_nombre_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_formato_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_formato)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_linea)
                    .addComponent(cb_linea_definicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_familia)
                    .addComponent(cb_familia_definicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(bt_guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_eliminar)
                .addGap(23, 23, 23))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarActionPerformed
        entityManager1.getTransaction().begin();
        Date d = new Date();
        Producto u = new Producto();
        u.setCodigoBarra(Integer.parseInt(tf_codigo_barra.getText()));
        u.setNombre(tf_nombre_producto.getText());
        u.setMarca(tf_nombre_marca.getText());
        u.setFormato(tf_formato_nombre.getText());
        u.setCreadoEl(d);
        u.setModificadoEl(d);
        u.setEliminadoEl(d);
        UnidadMedida un = (UnidadMedida)cb_unidad_medida.getSelectedItem();
        u.setUnidadMedidaId(un);
        Linea l = (Linea)cb_linea_definicion.getSelectedItem();
        u.setLineaId(l);
        Familia fa = (Familia)cb_familia_definicion.getSelectedItem();
        u.setFamiliaId(fa);
        JOptionPane.showMessageDialog(null,"Se a guardado correctamente");
        this.dispose();
        
        entityManager1.persist(u);
        entityManager1.flush();
        entityManager1.getTransaction().commit();
        entityManager1.close();
    }//GEN-LAST:event_bt_guardarActionPerformed

    private void bt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarActionPerformed

        Integer id = Integer.parseInt(this.tf_codigo_barra.getText());

        String qlQuery = "SELECT p FROM Producto p  WHERE p.codigoBarra =" + id;
        entityManager1.getTransaction().begin();
        Query query = entityManager1.createQuery(qlQuery);
        List<Producto> pr = query.getResultList();
        entityManager1.getTransaction().commit();
        Iterator<Producto> iter = pr.iterator();

        while (iter.hasNext()) {

            Producto p = (Producto) iter.next();

            idproducto = p.getId();
            String dato = String.valueOf(p.getNombre());
            String dato1 = String.valueOf(p.getCodigoBarra());
            String dato2 = String.valueOf(p.getUnidadMedidaId());
            String dato3 = String.valueOf(p.getMarca());
            String dato4 = String.valueOf(p.getFormato());
            String dato5 = String.valueOf(p.getLineaId());
            String dato6 = String.valueOf(p.getFamiliaId());
            
            tf_codigo_barra.setText(dato1);
            tf_nombre_producto.setText(dato);
            cb_unidad_medida.setSelectedItem(dato2);
            tf_nombre_marca.setText(dato3);
            tf_formato_nombre.setText(dato4);
            cb_linea_definicion.setSelectedItem(dato5);
            cb_familia_definicion.setSelectedItem(dato6);
        }
        
    }//GEN-LAST:event_bt_buscarActionPerformed
     
    
    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
        entityManager1.getTransaction().begin();
 
        Date d = new Date();
        Producto u = new Producto();
        
        u.setCodigoBarra(Integer.parseInt(tf_codigo_barra.getText()));
        u.setNombre(tf_nombre_producto.getText());
        u.setMarca(tf_nombre_marca.getText());
        u.setFormato(tf_formato_nombre.getText());
        u.setCreadoEl(d);
        u.setModificadoEl(d);
        u.setEliminadoEl(d);
        UnidadMedida un = (UnidadMedida)cb_unidad_medida.getSelectedItem();
        u.setUnidadMedidaId(un);
        Linea l = (Linea)cb_linea_definicion.getSelectedItem();
        u.setLineaId(l);
        Familia fa = (Familia)cb_familia_definicion.getSelectedItem();
        u.setFamiliaId(fa);
        JOptionPane.showMessageDialog(null,"Se a actualizado correctamente");
        this.dispose();
        
        entityManager1.persist(u);
        entityManager1.flush();
        entityManager1.getTransaction().commit();
        entityManager1.close();
    }//GEN-LAST:event_bt_editarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager Proyecto2PUEntityManager;
    private javax.swing.JButton bt_buscar;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_guardar;
    private javax.swing.JComboBox<String> cb_familia_definicion;
    private javax.swing.JComboBox<String> cb_linea_definicion;
    private javax.swing.JComboBox<String> cb_unidad_medida;
    private javax.persistence.EntityManager entityManager1;
    private java.util.List<Data.Familia> familiaList;
    private javax.persistence.Query familiaQuery;
    private javax.swing.JLabel lb_codigo_barra;
    private javax.swing.JLabel lb_familia;
    private javax.swing.JLabel lb_formato;
    private javax.swing.JLabel lb_linea;
    private javax.swing.JLabel lb_marca;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JLabel lb_unidad_medida;
    private java.util.List<Data.Linea> lineaList;
    private java.util.List<Data.Linea> lineaList1;
    private javax.persistence.Query lineaQuery;
    private javax.persistence.Query lineaQuery1;
    private javax.swing.JTextField tf_codigo_barra;
    private javax.swing.JTextField tf_formato_nombre;
    private javax.swing.JTextField tf_nombre_marca;
    private javax.swing.JTextField tf_nombre_producto;
    private java.util.List<Data.UnidadMedida> unidadMedidaList;
    private javax.persistence.Query unidadMedidaQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
