/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;



/**
 *
 * @author Matia
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Menu() {
        initComponents();
        
        /**
        Login l = new Login();
        if (l.logeado.equals("no")) {
            this.editMenu.setVisible(false);
            this.helpMenu.setVisible(false);
        } else if (l.logeado.equals("si")) {
            this.editMenu.setVisible(true);
            this.helpMenu.setVisible(true);
        }
        */ 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        ps_login = new javax.swing.JMenuItem();
        ps_registro = new javax.swing.JMenuItem();
        ps_salir = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        ps_add_producto = new javax.swing.JMenuItem();
        ps_add_valores = new javax.swing.JMenuItem();
        ps_add_produccion = new javax.swing.JMenuItem();
        ps_add_medidas = new javax.swing.JMenuItem();
        ps_add_recetas = new javax.swing.JMenuItem();
        ps_add_costos = new javax.swing.JMenuItem();
        ps_add_familia = new javax.swing.JMenuItem();
        ps_add_linea = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        ps_reporte_todo = new javax.swing.JMenuItem();
        ps_reporte_pan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Usuario");

        ps_login.setMnemonic('o');
        ps_login.setText("Ingresar Usuario");
        ps_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps_loginActionPerformed(evt);
            }
        });
        fileMenu.add(ps_login);

        ps_registro.setMnemonic('s');
        ps_registro.setText("Registar Usuario");
        ps_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps_registroActionPerformed(evt);
            }
        });
        fileMenu.add(ps_registro);

        ps_salir.setMnemonic('x');
        ps_salir.setText("Salir");
        ps_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps_salirActionPerformed(evt);
            }
        });
        fileMenu.add(ps_salir);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Ingresos");

        ps_add_producto.setMnemonic('t');
        ps_add_producto.setText("Ingreso de Producto");
        ps_add_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps_add_productoActionPerformed(evt);
            }
        });
        editMenu.add(ps_add_producto);

        ps_add_valores.setMnemonic('y');
        ps_add_valores.setText("Ingreso de Valores");
        ps_add_valores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps_add_valoresActionPerformed(evt);
            }
        });
        editMenu.add(ps_add_valores);

        ps_add_produccion.setMnemonic('p');
        ps_add_produccion.setText("Ingreso de Produccion");
        ps_add_produccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps_add_produccionActionPerformed(evt);
            }
        });
        editMenu.add(ps_add_produccion);

        ps_add_medidas.setMnemonic('d');
        ps_add_medidas.setText("Ingreso de Medidas");
        ps_add_medidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps_add_medidasActionPerformed(evt);
            }
        });
        editMenu.add(ps_add_medidas);

        ps_add_recetas.setText("Ingreso de Recetas");
        ps_add_recetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps_add_recetasActionPerformed(evt);
            }
        });
        editMenu.add(ps_add_recetas);

        ps_add_costos.setText("Ingreso de Costos");
        ps_add_costos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps_add_costosActionPerformed(evt);
            }
        });
        editMenu.add(ps_add_costos);

        ps_add_familia.setText("Ingreso de Familia");
        ps_add_familia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps_add_familiaActionPerformed(evt);
            }
        });
        editMenu.add(ps_add_familia);

        ps_add_linea.setText("Ingreso de Linea");
        ps_add_linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps_add_lineaActionPerformed(evt);
            }
        });
        editMenu.add(ps_add_linea);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Reportes");

        ps_reporte_todo.setMnemonic('c');
        ps_reporte_todo.setText("Reporte de Productos");
        ps_reporte_todo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps_reporte_todoActionPerformed(evt);
            }
        });
        helpMenu.add(ps_reporte_todo);

        ps_reporte_pan.setMnemonic('a');
        ps_reporte_pan.setText("Reporte Segun Producto");
        ps_reporte_pan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps_reporte_panActionPerformed(evt);
            }
        });
        helpMenu.add(ps_reporte_pan);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ps_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ps_salirActionPerformed

    private void ps_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps_loginActionPerformed
        Login internal = new Login();

        internal.pack();
        internal.setResizable(true);
        internal.setClosable(true);
        desktopPane.add(internal);
        internal.setVisible(true);
    }//GEN-LAST:event_ps_loginActionPerformed

    private void ps_add_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps_add_productoActionPerformed
        IngresoProducto internal = new IngresoProducto();

        internal.pack();
        internal.setResizable(true);
        internal.setClosable(true);
        desktopPane.add(internal);
        internal.setVisible(true);
    }//GEN-LAST:event_ps_add_productoActionPerformed

    private void ps_add_valoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps_add_valoresActionPerformed
        IngresoPrecio internal = new IngresoPrecio();

        internal.pack();
        internal.setResizable(true);
        internal.setClosable(true);
        desktopPane.add(internal);
        internal.setVisible(true);
    }//GEN-LAST:event_ps_add_valoresActionPerformed

    private void ps_add_produccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps_add_produccionActionPerformed
        IngresoProduccion internal = new IngresoProduccion();

        internal.pack();
        internal.setResizable(true);
        internal.setClosable(true);
        desktopPane.add(internal);
        internal.setVisible(true);
    }//GEN-LAST:event_ps_add_produccionActionPerformed

    private void ps_add_medidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps_add_medidasActionPerformed
        IngresoUnidadMedida internal = new IngresoUnidadMedida();

        internal.pack();
        internal.setResizable(true);
        internal.setClosable(true);
        desktopPane.add(internal);
        internal.setVisible(true);
    }//GEN-LAST:event_ps_add_medidasActionPerformed

    private void ps_add_recetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps_add_recetasActionPerformed
        IngresoReceta internal = new IngresoReceta();

        internal.pack();
        internal.setResizable(true);
        internal.setClosable(true);
        desktopPane.add(internal);
        internal.setVisible(true);
    }//GEN-LAST:event_ps_add_recetasActionPerformed

    private void ps_add_costosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps_add_costosActionPerformed
        IngresoCostos internal = new IngresoCostos();

        internal.pack();
        internal.setResizable(true);
        internal.setClosable(true);
        desktopPane.add(internal);
        internal.setVisible(true);
    }//GEN-LAST:event_ps_add_costosActionPerformed

    private void ps_add_familiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps_add_familiaActionPerformed
        IngresoFamilia internal = new IngresoFamilia();

        internal.pack();
        internal.setResizable(true);
        internal.setClosable(true);
        desktopPane.add(internal);
        internal.setVisible(true);
    }//GEN-LAST:event_ps_add_familiaActionPerformed

    private void ps_add_lineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps_add_lineaActionPerformed
        IngresoLinea internal = new IngresoLinea();

        internal.pack();
        internal.setResizable(true);
        internal.setClosable(true);
        desktopPane.add(internal);
        internal.setVisible(true);
    }//GEN-LAST:event_ps_add_lineaActionPerformed

    private void ps_reporte_todoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps_reporte_todoActionPerformed
        ReporteTodo internal = new ReporteTodo();

        internal.pack();
        internal.setResizable(true);
        internal.setClosable(true);
        desktopPane.add(internal);
        internal.setVisible(true);
    }//GEN-LAST:event_ps_reporte_todoActionPerformed

    private void ps_reporte_panActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps_reporte_panActionPerformed
        ReporteTipoPan internal = new ReporteTipoPan();

        internal.pack();
        internal.setResizable(true);
        internal.setClosable(true);
        desktopPane.add(internal);
        internal.setVisible(true);
    }//GEN-LAST:event_ps_reporte_panActionPerformed

    private void ps_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps_registroActionPerformed
        Registro internal = new Registro();

        internal.pack();
        internal.setResizable(true);
        internal.setClosable(true);
        desktopPane.add(internal);
        internal.setVisible(true);
    }//GEN-LAST:event_ps_registroActionPerformed
    
    public void login_menu() {
        initComponents();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    public javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    public javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem ps_add_costos;
    private javax.swing.JMenuItem ps_add_familia;
    private javax.swing.JMenuItem ps_add_linea;
    private javax.swing.JMenuItem ps_add_medidas;
    private javax.swing.JMenuItem ps_add_produccion;
    private javax.swing.JMenuItem ps_add_producto;
    private javax.swing.JMenuItem ps_add_recetas;
    private javax.swing.JMenuItem ps_add_valores;
    private javax.swing.JMenuItem ps_login;
    private javax.swing.JMenuItem ps_registro;
    private javax.swing.JMenuItem ps_reporte_pan;
    private javax.swing.JMenuItem ps_reporte_todo;
    private javax.swing.JMenuItem ps_salir;
    // End of variables declaration//GEN-END:variables

}
